# Óptica Geométrica

In [28]:
from __future__ import print_function
%matplotlib notebook
#%matplotlib inline

from numpy import sin, cos
import numpy as np
import matplotlib.pyplot as plt
#import ipywidgets as widgets
from scipy import stats

Lei de Snell $n_i \sin{\theta_i} =  n_t \sin{\theta_t}$

In [9]:
theta_i = np.array([10, 20, 30, 40, 50,]) /180*np.pi 
sin_theta_i = np.sin(theta_i )
sin_theta_i

array([0.17364818, 0.34202014, 0.5       , 0.64278761, 0.76604444])

In [31]:
theta_t_dir = np.array([6.5, 13, 20, 25.5, 31.5,]) 
theta_t_esq = np.array([8.5, 15, 21.5, 27.5, 32.5,]) 
theta_t_mean =  (theta_t_esq + theta_t_dir)/2.0
sin_theta_t_mean = np.sin(theta_t_mean/180*np.pi)
theta_t_err =  np.abs((theta_t_esq - theta_t_dir)/2.0)
len(theta_t_dir)
theta_t_err
#np.ones(len(theta_t_dir))
#np.min(np.ones(len(theta_t_dir)), theta_t_err)

array([1.  , 1.  , 0.75, 1.  , 0.5 ])

In [32]:
sin_theta_t_mean

array([0.13052619, 0.2419219 , 0.35429104, 0.44619781, 0.52991926])

In [33]:
x=sen_theta_i
y=sin_theta_t_mean

slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)
print("slope:%g" %slope)
print("intercept:%g V" %intercept)
#print 'Vel= %g' %Var
#print("slope:", slope)
print("r-squared:", r_value**2)
print("p_value:", p_value)
print("slope std_err:%g" %std_err)

slope:0.675379
intercept:0.01308 V
r-squared: 0.9998183587045238
p_value: 1.0390451446776403e-06
slope std_err:0.00525574


## Equação focos conjugados
$ \frac{1}{f} = \frac{1}{D_{Obj}} + \frac{1}{D_{Im}}$ ou  $ f = \frac{D_{Obj} D_{Im}}{D_{Obj} + D_{Im}} $

Formula Newton (distâncias aos focos): $$ f^2 = x_{Obj} \cdot x_{Im}  $$ 

In [2]:
def focosConj_di(f,do):
    xo=do-f
    xi=f/xo
    di=f+xi
    A=-di/do
    return di,A

In [3]:
fc=1
dObj=1.5
dIm,Amp =focosConj_di(fc,dObj)
print("DObj=%g, DIm=%g, Ampl=%g" %(dObj,dIm,Amp ))

DObj=1.5, DIm=3, Ampl=-2


In [39]:
Dobj=120.
Dimg=328.
fconv=(Dobj*Dimg)/(Dobj+Dimg)
print("fconv=%g" %(fconv ))

fconv=87.8571


## Cálculo da distância Focal da Lente Divergente
$$ \frac{1}{f_{Equ}} = \frac{1}{f_{Conv}} + \frac{1}{f_{Div}} + \frac{D_{Lentes}}{f_{Conv} f_{Div}}  $$
$$ \frac{1}{f_{Equ}} =  \frac{f_{Div} + f_{Conv}   + D_{Lentes}}{f_{Conv} f_{Div}}  $$
$$ f_{Div} = \frac{f_{Equ} (f_{Conv} - D_{Lentes} ) }{ f_{Conv} -f_{Equ}}   $$