# Experiência de Thomson. 
## Determinação experimental da relação q/m do electrão

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
from scipy import constants # Constantes Físicas
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
#np.set_printoptions(precision=4)

### DETERMINAÇÃO DE q/m POR DEFLEXÃO MAGNÉTICA

Raio da Trajectória: $R=\frac{y^2 + z^2}{2z}$

In [5]:
def Rt(y, z):
    return (y**2 + z**2)/(2*z)

Coordenadas no ecran

In [6]:
import ipywidgets as widgets
tetha=np.linspace(0, np.pi/2, 100) 
spacing = 0.01
minorLocator = MultipleLocator(spacing)
#ax.
def plotR(raio):
    y=raio*np.sin(tetha)
    z=raio*(1-np.cos(tetha))
    plt.plot(y, z)
    ax = plt.gca()
    ax.xaxis.set_minor_locator(minorLocator)
    ax.yaxis.set_minor_locator(minorLocator)
    ax.grid(which = 'minor')
    plt.axis('equal')
    plt.grid('on')
    plt.tick_params
    plt.plot(y, z, label='Trajectoria')
    plt.legend(loc='upper center')
    plt.axis([0.10, 0.0, -0.05, 0.05])   # [tmin, tmax, ymin, ymax]
    plt.show()
    
widgets.interact(plotR, raio=(0.1,0.6,0.001));

A Jupyter Widget

In [7]:
yt=np.array([0.10, 0.10, 0.09, 0.09, 0.08])
zt=np.array([0.01, 0.02, 0.01, 0.02, 0.01])

In [8]:
Raio=Rt(yt,zt)
Raio

array([ 0.505 ,  0.26  ,  0.41  ,  0.2125,  0.325 ])

Campo Magnético $B_x = \left(\frac{4}{5}\right)^{3/2} \cdot \frac{\mu_0 n }{r} I$

In [9]:
nHel=320 # espiras 
rHel = 0.068 # raio bobinas de Helmholtz

Medidas

In [10]:
IHel=np.array([0.100,0.040, 0.2,0.3 , 0.25])

In [11]:
def Bx(I, n,r):
    return (4.0/5)**(3/2)*constants.mu_0*n/r*I

In [12]:
campoB=Bx(IHel, nHel, rHel)
campoB

array([ 0.00047309,  0.00018923,  0.00094617,  0.00141926,  0.00118272])

Razão q/m : $\frac{q}{m} = \frac{2\, U_a}{B^2\,R^2}$

In [13]:
def q_m(U,B,R):
    return 2*U/B**2/R**2

In [14]:
Ua=4500.0

In [15]:
qm=q_m(Ua,campoB,Raio)
qm

array([  1.57680475e+11,   3.71786827e+12,   5.98043771e+10,
         9.89464684e+10,   6.09135537e+10])

## Cálculo de Incertezas
### cálculo simbólico de derivadas parciais

In [16]:
import sympy as sp
from scipy.misc import derivative
from sympy.parsing.sympy_parser import parse_expr

In [17]:
eqRaio= '(y**2 + z**2)/(2*z)'
y, z = sp.symbols('y z')

In [18]:
dPy = sp.diff(eqRaio , y)
print dPy

y/z


In [19]:
dPz = sp.diff(eqRaio , z)
print dPz

1 - (y**2 + z**2)/(2*z**2)


In [20]:
print sp.latex(dPz)

1 - \frac{y^{2} + z^{2}}{2 z^{2}}


$$1 - \frac{y^{2} + z^{2}}{2 z^{2}}$$


In [21]:
def errRtlin(y, ey, z, ez):
    return np.abs(y/z)*ey + np.abs(1 - (y**2 + z**2)/(2*z**2))*ez

### Incertezas das Medidas

In [22]:
errRtlin(yt, 0.005, zt, 0.001)

array([ 0.0995  ,  0.037   ,  0.085   ,  0.032125,  0.0715  ])

In [23]:
eqQm= '2*U/B**2/R**2'
U, B, R= sp.symbols('U B R')

In [24]:
dPQmU = sp.diff(eqQm , U)
dPQmU

2/(B**2*R**2)

In [25]:
dPQmB = sp.diff(eqQm , B)
dPQmB

-4*U/(B**3*R**2)

In [26]:
dPQmR = sp.diff(eqQm , R)
dPQmR

-4*U/(B**2*R**3)

In [27]:
def errQmLin(U,eU, B, eB ,R, eR):
    return np.abs(2/(B**2*R**2))*eU  + 4*U/(B**3*R**2)*eB  + 4*U/(B**2*R**3)*eR

In [28]:
errQmLin(4500, 250.0, campoB, 1e-4 ,Raio, 0.0995)

array([  1.37555760e+11,   6.98151886e+12,   4.49907772e+10,
         1.12100865e+11,   5.09825353e+10])

## Campos Magnético e Elétrico não compensados

http://farside.ph.utexas.edu/teaching/336k/Newtonhtml/node30.html

In [32]:
Ve=np.sqrt(2/constants.m_e*constants.e*Ua) # Velocidade do electrão à saida do ânodo<
E=Ua/0.05 # Campo electrico
campoB[0]
B=0.01 # T
#Ve/constants.c
#VEB=E*B/B**2  # Vel. de deriva
#VEB/constants.c
#RL = Ve / Fcic # raio de Larmor
#print "Rlarmor =%g" % RL

0.00047308689371705116

In [33]:
timen=np.linspace(0, 20*np.pi, 200)
def plotCic(B):
    Fcic=constants.e/constants.m_e * B # Freq ciclotronica /  rad/s
    time=timen/Fcic
    RL = Ve / Fcic # raio de Larmor
    yp=RL*np.sin(time * Fcic)
    z=RL*(1-np.cos(time * Fcic))
    VEB=E*B/B**2  # Vel. de deriva
    y=yp + time * VEB
    plt.plot(y, z)
    plt.axis('equal')
    plt.grid('on')
    plt.tick_params
    plt.plot(y, z, label='Cicloide')
    plt.axis([0.10, 0.0, -0.02, 0.05])   # [ymin, ymax, zmin, zmax]
    plt.legend(loc='upper center')
    plt.show()
widgets.interact(plotCic, B=(0.001,0.04,0.001));

A Jupyter Widget