# Experiência de Thomson. 
## Determinação experimental da relação q/m do electrão

In [136]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
#import sympy as spy
from scipy import constants # Constantes Físicas
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### DETERMINAÇÃO DE q/m POR DEFLEXÃO MAGNÉTICA

Raio da Trajectória: $R=\frac{y^2 + z^2}{2z}$

In [137]:
def Rt(y, z):
    return (y**2 + z**2)/(2*z)

Coordenadas no ecran

In [164]:
yt=np.array([0.10, 0.10, 0.09, 0.09, 0.08])
zt=np.array([0.01, 0.02, 0.01, 0.02, 0.01])

In [165]:
#for i in range(len(y)):
#    Raio[i]=R(y,z)
Raio=Rt(yt,zt)
Raio

array([ 0.505 ,  0.26  ,  0.41  ,  0.2125,  0.325 ])

Campo Magnetico $B_x = \left(\frac{4}{5}\right)^{3/2} \cdot \frac{\mu_0 n }{r} I$

In [140]:
nHel=320 # espiras 
rHel = 0.068 # raio bobinas de Helmholtz

Medidas

In [141]:
IHel=np.array([0.100,0.040, 0.2,0.3 , 0.25])

array([ 0.1 ,  0.04,  0.2 ,  0.3 ,  0.25])

In [142]:
def Bx(I, n,r):
    return (4.0/5)**(3/2)*constants.mu_0*n/r*I

In [143]:
campoB=Bx(IHel,nHel,rHel)
campoB

array([ 0.00047309,  0.00018923,  0.00094617,  0.00141926,  0.00118272])

Relação q/m  $\frac{q}{m} = \frac{2\, U_a}{B^2\,R^2}$

In [144]:
def q_m(U,B,R):
    return 2*U/B**2/R**2

In [145]:
Ua=4500.0

In [146]:
qm=q_m(Ua,campoB,Raio)
qm

array([  1.57680475e+11,   3.71786827e+12,   6.12750130e+06,
         1.08852720e+07,   6.28123433e+06])

## Cálculo de Incertezas
### cálculo simbólico de derivadas parciais

In [147]:
import sympy as sp
from scipy.misc import derivative
from sympy.parsing.sympy_parser import parse_expr

In [148]:
#eq = 'k*a*b**2/c**2'
eqRaio= '(y**2 + z**2)/(2*z)'
#a = sp.Symbol('a')
#%b = sp.Symbol('b')
#%c = sp.Symbol('c')
y, z = sp.symbols('y z')

In [149]:
dPy = sp.diff(eqRaio , y)
print dPy

y/z


In [150]:
dPz = sp.diff(eqRaio , z)
print dPz

1 - (y**2 + z**2)/(2*z**2)


In [151]:
print sp.latex(dPz)

1 - \frac{y^{2} + z^{2}}{2 z^{2}}


$$1 - \frac{y^{2} + z^{2}}{2 z^{2}}$$


In [152]:
def errRtlin(y, ey, z, ez):
    return np.abs(y/z)*ey + np.abs(1 - (y**2 + z**2)/(2*z**2))*ez

Incertezas da Medidas

In [153]:
errRtlin(yt, 0.005, zt, 0.001)

array([ 0.0995,  0.037 ,  4.4995,  1.237 ,  3.5995])

In [154]:
eqQm= '2*U/B**2/R**2'
U, B, R= sp.symbols('U B R')

In [155]:
dPQmU = sp.diff(eqQm , U)
dPQmU

2/(B**2*R**2)

In [156]:
dPQmB = sp.diff(eqQm , B)
dPQmB

-4*U/(B**3*R**2)

In [157]:
dPQmR = sp.diff(eqQm , R)
dPQmR

-4*U/(B**2*R**3)

In [158]:
def errQmLin(U,eU, B, eB ,R, eR):
    return np.abs(2/(B**2*R**2))*eU  + 4*U/(B**3*R**2)*eB  + 4*U/(B**2*R**3)*eR

In [159]:
errQmLin(4500, 250.0, campoB, 1e-4 ,Raio, 0.0995)

array([  1.37555760e+11,   6.98151886e+12,   1.66573787e+06,
         2.24559138e+06,   1.45018287e+06])

<function __main__.Rt>

2